# Generated by Django 2.1 on 2018-10-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='tiposDeServicio',
            field=models.ForeignKey(choices=[(1, 'Desarrollador Web'), (2, 'Option 2')], null=True, on_delete=django.db.models.deletion.PROTECT, to='Website.TiposDeServicio'),
        ),
    ]
