# Generated by Django 2.1 on 2018-10-08 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20181007_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='tiposDeServicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Website.TiposDeServicio'),
        ),
    ]
